### ISSUE TITLE
Doesn't seem to work with kivy - 'LogFile' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by stuaxo** [staticshock/colored-traceback.py#2]
```
'LogFile' object has no attribute 'isatty'
 Traceback (most recent call last):
WARNING:kivy:stderr: Traceback (most recent call last):
   File "/mnt/data/home/stu/projects/mine/apcmm/apcmm/emulator/__init__.py", line 6, in main
WARNING:kivy:stderr:   File "/mnt/data/home/stu/projects/mine/apcmm/apcmm/emulator/__init__.py", line 6, in main
     from main import main as emumain
WARNING:kivy:stderr:     from main import main as emumain
   File "/mnt/data/home/stu/projects/mine/apcmm/apcmm/emulator/main.py", line 16, in <module>
WARNING:kivy:stderr:   File "/mnt/data/home/stu/projects/mine/apcmm/apcmm/emulator/main.py", line 16, in <module>
     import colored_traceback; colored_traceback.add_hook()
WARNING:kivy:stderr:     import colored_traceback; colored_traceback.add_hook()
   File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/colored_traceback/colored_traceback.py", line 5, in add_hook
WARNING:kivy:stderr:   File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/colored_traceback/colored_traceback.py", line 5, in add_hook
     if sys.stderr.isatty() or always:
WARNING:kivy:stderr:     if sys.stderr.isatty() or always:
 AttributeError: 'LogFile' object has no attribute 'isatty'
WARNING:kivy:stderr: AttributeError: 'LogFile' object has no attribute 'isatty'
```

**Comment by stuaxo** [comment]
Thanks, doesn't crash any more .. traceback doesn't seem to be in colour though - maybe kivy has it's own hook traceback handling I don't know about :/

**Comment by staticshock** [comment]
It's overwriting `stderr` with a `LogFile` class.

If you _know_ that your output is actually going to a terminal, feel free to use `colored_traceback.add_hook(always=True)` (described in README.) But if it's going to a log file, that log file will have ANSI escape sequence gunk in it.
